// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";

// Prisma CLI reads .env files automatically, but this ensures it's explicit
// especially if you have different env files.
dotenv.config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // This is where connection URLs now live.
  // We provide both singular and plural forms for compatibility with different Prisma commands.
  datasources: {
    db: { url: env("DATABASE_URL"), directUrl: env("DATABASE_URL_UNPOOLED") },
  },
  // Fallback for commands that might expect the singular form.
  datasource: { url: env("DATABASE_URL"), directUrl: env("DATABASE_URL_UNPOOLED") },
});
